language: node_js
node_js:
  - "8.9.4"

cache:
  directories:
    - node_modules
    - server/node_modules

before_script:
  - npm install
  - npm --prefix ./server install

script:
  - npm run build --prod
  - npm run lint
  - npm --prefix ./server run build
  - npm --prefix ./server run lint
  - npm --prefix ./server test
