language: node_js
node_js:
  - "8.9.4"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli
  - npm install
  - npm --prefix ./server install

script:
  - ng build
  - ng lint
  - npm --prefix ./server run build
  - npm --prefix ./server run lint
  - npm --prefix ./server test
