# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 13:49
from __future__ import unicode_literals

import codasubmission.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codacontest', '0001_initial'),
        ('codaproblem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('contestBatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codacontest.ContestBatch')),
            ],
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionTime', models.DateTimeField(auto_now_add=True)),
                ('source', models.FileField(upload_to=codasubmission.models.getSubmissionPath)),
                ('mainClass', models.CharField(max_length=200)),
                ('language', models.ManyToManyField(to='codaproblem.Language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='codacontest.ContestProblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('contestProblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codacontest.ContestProblem')),
            ],
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('isSuccess', models.BooleanField()),
                ('isPending', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestFileResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultTime', models.DateTimeField(auto_now_add=True)),
                ('userOutput', models.FileField(upload_to=codasubmission.models.getUserOutputPath)),
                ('memoryUsedBytes', models.BigIntegerField()),
                ('timeUsedMS', models.BigIntegerField()),
                ('batchResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codasubmission.BatchResult')),
            ],
        ),
        migrations.CreateModel(
            name='TestFileResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('isSuccess', models.BooleanField()),
                ('isPending', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='testfileresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codasubmission.TestFileResultType'),
        ),
        migrations.AddField(
            model_name='testfileresult',
            name='testFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codaproblem.TestFile'),
        ),
        migrations.AddField(
            model_name='problemresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codasubmission.ResultType'),
        ),
        migrations.AddField(
            model_name='problemresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codasubmission.ContestSubmission'),
        ),
        migrations.AddField(
            model_name='batchresult',
            name='problemResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codasubmission.ProblemResult'),
        ),
        migrations.AddField(
            model_name='batchresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codasubmission.ResultType'),
        ),
    ]
