# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:11
from __future__ import unicode_literals

import codaproblem.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codaauth', '0001_initial'),
        ('codaproblem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codaauth.CodaUser'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='checker',
            field=models.FileField(null=True, upload_to=codaproblem.models.getProblemPath),
        ),
        migrations.AlterField(
            model_name='problem',
            name='checkerType',
            field=models.ForeignKey(default='diff', on_delete=django.db.models.deletion.CASCADE, to='codaproblem.CheckerType'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='usePDF',
            field=models.BooleanField(default=False),
        ),
    ]
