# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:04
from __future__ import unicode_literals

import codaproblem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codaproblem', '0002_auto_20160107_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pdfStatement',
            field=models.FileField(null=True, upload_to=codaproblem.models.getProblemPath),
        ),
    ]
